### ISSUE TITLE
Mockup II

### ISSUE THREAD

**Issue by arildm** [CDH-DevTeam/queerlit-gui#1]
Mockup I was done in October 2021 and looked [like this (image)](https://user-images.githubusercontent.com/1454404/146954656-2d4d4761-01c5-44b6-b0d2-459bba2b99ea.png).

A second mockup should be presented at the Feb 1 meeting.

- [x] Simple filter inputs for: QLIT terms, title, author, year, genre/form
- [ ] ~Add autocomplete to these filter inputs: title, author, genre/form~ #2, #3
- [ ] ~Add range slider for year filter~ #4 
- [ ] ~Combobox for QLIT terms with drilldown, more info, preferred terms~ #11
- [ ] ~Add fuzzy matching to all autocomplete inputs~ #6 
- [x] Link to Libris for single post
- [ ] ~Link to Libris for a search query~ #7 
- [ ] ~Links to full texts if they exist in Libris~ #8 
- [ ] ~(Links to) user manual~ #9 
- [ ] ~(Links to) making suggestions~ #10
